### ISSUE TITLE
You should be able to validate each item in a simple array

### ISSUE THREAD

**Issue by balaclark** [serby/schemata#26]
I wanted to validate each item in a property with the type of `Array`, but this currently doesn't seem to be possible. You can only do it if you use `schemata.Array` and save each item as a schemata subschema like: `schemata.Array(subSchema)`.

I have written a custom validator to serve this purpose, but this feels like something that should go into schemata itself.

My validator is not published yet, but here is an example unit test:

```js
var assert = require('assert-diff')
  , required = require('validity').required
  , createValidator = require('./validate-each')

describe('Validity Validate Each', function () {

  it('should apply a given validator to each value of an array', function (done) {
    var obj = { test: [ 1, 2, '', null, 5 ] }

    createValidator(required)('test', 'Test Property', obj, function (err, msgs) {
      assert.deepEqual(msgs, { 2: 'Test Property is required', 3: 'Test Property is required' })
      done()
    })

  })
})
```

**Comment by serby** [comment]
I would not expect the errors to be keyed using the values but the index they appear in the array like so:

```js
var assert = require('assert-diff')
  , required = require('validity').required
  , createValidator = require('./validate-each')

describe('Validity Validate Each', function () {

  it('should apply a given validator to each value of an array', function (done) {
    var obj = { test: [ 1, 2, '', null, 5 ] }

    createValidator(required)('test', 'Test Property', obj, function (err, msgs) {
      assert.deepEqual(msgs, { 1: 'Test Property is required', 2: 'Test Property is required' })
      done()
    })

  })
})
```

Imagine the following input. It would be very hard to reason about which array indexes had failed. 
```js
var obj = { test: [ 1, 2, '', null, 5, 2, null, 1, 5 ] }
```

Also I think this should remain in a validator and not in schemata. But is should allow compound validations 

Like so:

Let's call it `validateEach`

```js
var schema = schemata(
  { _id:
    { type: String
    }
  , name:
    { type: String
    }
  , emailAddresses:
    { type: Array
    , validators: { all: [ validateEach(validity.email) ] }
    })
```

**Comment by balaclark** [comment]
The messages are already keyed by index starting at 0, the test above shows this as the failures are in index 2 and 3, and the resulting error object has messages at those keys.

I already named it validateEach :wink:, I'll move it out of T+ and into an npm module.

**Comment by serby** [comment]
@balaclark Sorry! I had number blindness. Ignore what I said. Except the part about 'not in schemata' and 'compound validations'

**Comment by balaclark** [comment]
I've published it as an npm module now: https://www.npmjs.com/package/validity-validate-each

**Comment by serby** [comment]
Great addition. Looking forward to using it!

Estoy en España ahora también.

On 5 July 2015 at 18:56, Bala Clark <notifications@github.com> wrote:

> I've published it as an npm module now:
> https://www.npmjs.com/package/validity-validate-each
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serby/schemata/issues/26#issuecomment-118638195>.
>



-- 

paul.serby@clock.co.uk
Chief Technology Officer


*Mobile: +44 7881 550999**Skype: paul.serby*
*Twitter: serby*
--


* <http://www.clock.co.uk/>*

The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
Switchboard: +44 1923 261166www.clock.co.uk


* <http://twitter.com/clock>    <https://github.com/clocklimited>
<http://www.linkedin.com/company/clock-limited>
<http://www.clock.co.uk/blog>*

*www.clock.co.uk/email-disclaimer <http://www.clock.co.uk/email-disclaimer>*
*clock.® is a Registered Trademark of Clock Limited in the European
Community and other territories*

**Comment by balaclark** [comment]
closing this as the issue was fixed via a module.
