### ISSUE TITLE
Type of content inside array

### ISSUE THREAD

**Issue by OliverJAsh** [serby/schemata#3]
I have a schema with a `subscriptions` property of type `Array`. This array should contain `ObjectId`s.

i.e.:

```
"subscriptions" : [     ObjectId("5139357f5fa21da32b000001"),   ObjectId("5139357f5fa21da32b000002"),   ObjectId("5139357f5fa21da32b000003"),   ObjectId("5139357f5fa21da32b000004") ]
```

At the moment it doesn't seem possible to define the content type of an `Array`. I need this because currently I'm doing something along the lines of this in my application (manually casting):

```
collection.update({}, { $set: { subscriptions: feeds.map(function (feed) {
  return new ObjectId(feed._id)
}) } }, function (err, users) {})
```

Unfortunately I don't have any suggestions for how the API should look…

**Comment by unusualbob** [comment]
How was this resolved? (Or was it ever resolved?)
