### ISSUE TITLE
Referential `defaultValue`s

### ISSUE THREAD

**Issue by bengourley** [serby/schemata#32]
Often people forget (or don't know) that you must use either a primitive value or a function to return any object/array type for `property.defaultValue`, eg:

```js
{ a: { type: Array, defaultValue: [] }
, b: { type: Object, defaultValue: {} }
}
```

```js
var obj = schemata.makeDefault()
obj.a.push('something')
obj.b.oops = 'this is bad'

var obj2 = schemata.makeDefault()
obj2.a.length //-> 1
obj2.b.oops //-> 'this is bad'
```

This happens often enough that I think schemata should either **cope** *or* **complain**.

So my suggested options are:

1. Throw an exception if `defaultValue` is not a) a function or b) a primitive type (number, string, null, undefined etc.)
2. Accept any input and deep clone any array/object types so that.

@serby, @microadam, @domharrington what do you think we should do?

**Comment by serby** [comment]
+1 it should be a primitive or function and throw if not

**Comment by serby** [comment]
I've never seen this issue, but it seem so obviously bad now you point it out.

**Comment by microadam** [comment]
I would say its developer error, so throwing seems logical, let them know straight away that what they are doing is considered bad practice. You could go the deep cloning route, but there is always a chance you are going to miss some edge case, throwing seems simpler

**Comment by bengourley** [comment]
I'm glad you both prefer `throw`, that's my preference too. I think we need to do a quick descend of the schema in the constructor so that we error as early as possible.

@serby we had this issue back in the early Catfish days and it's bitten us intermittently ever since.
